services:
    app:
        build: ./
        command: streamlit run webapp/app.py --server.port 8501 --server.headless true
        volumes:
            - ./aforo:/app/aforo
            
        ports:
            - 8501:8501
        image: termariavisualizer:latest
